FROM registry.access.redhat.com/ubi8/openjdk-8:1.11-1.1648459552

COPY ${pwd}/target/ocpdemo-0.0.1-SNAPSHOT.jar /home/jboss/rest-0.0.1.jar

USER root

RUN chown jboss:root /home/jboss && \
    chmod -R 755 /home/jboss/rest-0.0.1.jar

USER jboss

CMD java -Djava.net.preferIPv4Stack=true -jar /home/jboss/rest-0.0.1.jar